### ISSUE TITLE
Support for CommonJS, Node and Npm

### ISSUE THREAD

**Issue by dynnamitt** [alexmilowski/green-turtle#3]
http://www.mattpalmerlee.com/2013/04/23/create-your-first-node-module-and-publish-it-to-the-npm-registry/

http://nodejs.org/docs/latest/api/modules.html

**Comment by elf-pavlik** [comment]
@alexmilowski jsonld.js supports it with node, i'll try to add package.json in a fork and then help with publishing it to npm!
https://github.com/digitalbazaar/jsonld.js/blob/master/js/request.js#L117

**Comment by ariutta** [comment]
+1

**Comment by betehess** [comment]
Any chance to fix that? In Scala.js, node.js is the preferred environment for testing.

**Comment by sballesteros** [comment]
FWIW, I started working on getting green-turtle to work as is in JSDOM in this pull request: https://github.com/alexmilowski/green-turtle/pull/7

**Comment by sballesteros** [comment]
Ok so I have extracted the GraphRDFaProcessor into its own commonJS module. See https://github.com/scienceai/graph-rdfa-processor. I made additional changes there so that it works both in the browser and JS-DOM.

**Comment by elf-pavlik** [comment]
@bergos maybe relevant for your
* https://github.com/rdf-ext/rdf-parser-microdata
* https://github.com/rdf-ext/rdf-parser-rdfa

**Comment by bergos** [comment]
@elf-pavlik I know this issue. I have already a [fix](https://github.com/bergos/green-turtle) for it, but I had problems getting the Green Turtle tests running, even without my changes.

**Comment by alexmilowski** [comment]
I've merged your pull request.
